### ISSUE TITLE
MaskCut leaves out some folders

### ISSUE THREAD

**Issue by khatanas** [facebookresearch/CutLER#24] opened 2023-04-11 10:41 UTC
Hello, thank you for sharing this nice work.

I am encountering an issue while running MaskCut on my dataset, as some folders are not being processed. I attached a picture of the masking process for a dummy dataset splitted into 10 folders of 2 images each. 

![bugMaskCut](https://user-images.githubusercontent.com/71390266/231131175-0b7850a1-830f-43c8-8a5b-37b7bb980e1b.PNG)

* This also happens when the 10 folders contain the exact same 2 pictures (1 out of 10 is left out)
* This also happens when I process the 5 first folders only (1 out of 5 is left out)
* This also happens when I process the 5 remaining folders (1 out of 5 is left out)

I'm not sure what could be causing this problem, would you have any suggestions ?

**Comment by frank-xwang** [comment] 2023-04-12 05:11
Hi, we haven't encountered this issue before. However, I suggest checking the error message by uncommenting the "try and except" code, which will skip the image if MaskCut fails to process it. It is hard for me to debug given the limited information on the images and the GPUs you are using. My current hypothesis is that this issue may be caused by an out-of-memory error. You can fix it using a GPU with a larger memory or a smaller image size by modifying the fixsize argument.

**Comment by frank-xwang** [comment] 2023-04-14 15:56
Closing it now, please feel free to reopen it if you have further questions.

**Closed by frank-xwang** 2023-04-14 15:56 UTC
