### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [facebookresearch/CutLER#4] opened 2023-01-27 15:06 UTC

**Comment by frank-xwang** [comment] 2023-01-27 17:22
duplicate of #5. closing it now.

**Closed by frank-xwang** 2023-01-27 17:22 UTC

**Comment by FrancescoSaverioZuppichini** [comment] 2023-01-28 18:53
Apologies, not sure how this happen - maybe duplicate tabs from my side

**Comment by frank-xwang** [comment] 2023-01-29 18:56
No worries! Good to know that it is working now!
