### ISSUE TITLE
Error with imports when using the notebook demo for maskcut

### ISSUE THREAD

**Issue by Copper76** [facebookresearch/CutLER#54] opened 2023-11-10 06:45 UTC
When I was trying out the demo for maskcut in jupyter notebook using the link in readme. I cannot seem to import the metric module from third_party.TokenCut.unsupervised_saliency_detection. The system path doesn't seem to work. I have tried work arounds but there is still an import in maskcut which I don't wish to disturb. Otherwise I haven't been able to find an elegant solution. Can you help me with it?

**Comment by frank-xwang** [comment] 2023-11-12 16:45
Hey, duplicate of another issue. Please check #50.

**Comment by Copper76** [comment] 2023-11-12 19:24
Hi, I have checked it. However, the issue persists even after me checking that third party has been successfully cloned and exists. I am using the recursive command for the clone, which was the case in the demo

**Comment by frank-xwang** [comment] 2023-11-13 17:05
Hi, can you add `sys.path.insert(0, "../third_party")` at the beginning of each file that imports third-party libraries? Additionally, change all instances of `import third_party.ABC` to simply `import ABC`. This should help resolve the issue. It appears to be related to using the latest Python version.

Let me know if this can fix your issue.

**Comment by Copper76** [comment] 2023-11-13 21:02
That does indeed solve the problem, thanks for the help.

**Closed** 2023-11-13 21:35 UTC
