### ISSUE TITLE
training slow

### ISSUE THREAD

**Issue by jxgu1016** [facebookresearch/CutLER#9] opened 2023-02-06 07:40 UTC
Hi, thanks for this good work.

I run the training on 8 A100 gpus and find it will cost almost 20 days to finish one round training. Is that normal? How much time it will cost you to train one round?

**Comment by jxgu1016** [comment] 2023-02-06 07:41
More details, the GPU Uitil. is very low

**Comment by frank-xwang** [comment] 2023-02-13 01:48
Closing it now. Please feel free to reopen it if you have any more questions.

**Closed by frank-xwang** 2023-02-13 01:48 UTC

**Comment by linyq2117** [comment] 2023-10-13 12:35
Hi, 

I also came across this problem during training. I changed the num_workers but the training time is still too long (more than 10 days). The GPU Uitill had no improvement by increasing num_workers. Did you solve it? @jxgu1016 @frank-xwang

**Comment by linyq2117** [comment] 2023-10-14 04:34
I find the reason. This problem is caused by the COPY_PASTE operation. It is operated on CPU and thus heavily slows down the training speed.
